const keyMap = {
    "32": {keyName: "Space", row: 'row5', allowInput: true},
    "8": {keyName: "Backspace", row: 'row1', allowInput: true},
    "9": {keyName: "Tab", row: 'row2', allowInput: false},
    "13": {keyName: "Enter", row: 'row3', allowInput: false},
    "16": {keyName: "LShift", row: 'row4', allowInput: false},
    "17": {keyName: "Ctrl", row: 'row5', allowInput: false},
    "18": {keyName: "lAlt", row: 'row5', allowInput: false},
    "20": {keyName: "Caps", row: 'row3', allowInput: false},
    "48": {keyName: "0 )", row: 'row1', allowInput: true},
    "49": {keyName: "1 !", row: 'row1', allowInput: true},
    "50": {keyName: "2 @", row: 'row1', allowInput: true},
    "51": {keyName: "3 #", row: 'row1', allowInput: true},
    "52": {keyName: "4 $", row: 'row1', allowInput: true},
    "53": {keyName: "5 %", row: 'row1', allowInput: true},
    "54": {keyName: "6 ^", row: 'row1', allowInput: true},
    "55": {keyName: "7 &", row: 'row1', allowInput: true},
    "56": {keyName: "8 *", row: 'row1', allowInput: true},
    "57": {keyName: "9 (", row: 'row1', allowInput: true},
    "65": {keyName: "a", row: 'row3', allowInput: true},
    "66": {keyName: "b", row: 'row4', allowInput: true},
    "67": {keyName: "c", row: 'row4', allowInput: true},
    "68": {keyName: "d", row: 'row3', allowInput: true},
    "69": {keyName: "e", row: 'row2', allowInput: true},
    "70": {keyName: "f", row: 'row3', allowInput: true},
    "71": {keyName: "g", row: 'row3', allowInput: true},
    "72": {keyName: "h", row: 'row3', allowInput: true},
    "73": {keyName: "i", row: 'row2', allowInput: true},
    "74": {keyName: "j", row: 'row3', allowInput: true},
    "75": {keyName: "k", row: 'row3', allowInput: true},
    "76": {keyName: "l", row: 'row3', allowInput: true},
    "77": {keyName: "m", row: 'row4', allowInput: true},
    "78": {keyName: "n", row: 'row4', allowInput: true},
    "79": {keyName: "o", row: 'row2', allowInput: true},
    "80": {keyName: "p", row: 'row2', allowInput: true},
    "81": {keyName: "q", row: 'row2', allowInput: true},
    "82": {keyName: "r", row: 'row2', allowInput: true},
    "83": {keyName: "s", row: 'row3', allowInput: true},
    "84": {keyName: "t", row: 'row2', allowInput: true},
    "85": {keyName: "u", row: 'row2', allowInput: true},
    "86": {keyName: "v", row: 'row4', allowInput: true},
    "87": {keyName: "w", row: 'row2', allowInput: true},
    "88": {keyName: "x", row: 'row4', allowInput: true},
    "89": {keyName: "y", row: 'row2', allowInput: true},
    "90": {keyName: "z", row: 'row4', allowInput: true},
    "59": {keyName: "; :", row: 'row3', allowInput: true},
    "61": {keyName: "= +", row: 'row1', allowInput: true},
    "173": {keyName: "- _", row: 'row1', allowInput: true},
    "188": {keyName: ", <", row: 'row4', allowInput: true},
    "189": {keyName: "- _", row: 'row1', allowInput: true},
    "190": {keyName: ". >", row: 'row4', allowInput: true},
    "191": {keyName: "/ ?", row: 'row4', allowInput: true},
    "192": {keyName: "` ~", row: 'row1', allowInput: true},
    "219": {keyName: "[ {", row: 'row2', allowInput: true},
    "220": {keyName: "\\ |", row: 'row2', allowInput: true},
    "221": {keyName: "] }", row: 'row2', allowInput: true},
    "222": {keyName: '\' "', row: 'row3', allowInput: true}
}

export default keyMap