export const INCORRECT_KEYSTROKE = 'INCORRECT_KEYSTROKE'
export const CORRECT_KEYSTROKE = 'CORRECT_KEYSTROKE'
export const BACKSPACE_PRESSED = 'BACKSPACE_PRESSED'

export const GAME_START = 'GAME_START'
export const ENTER_ROOM_START = 'ENTER_ROOM_START'
export const ENTER_ROOM_SUCCESS = 'ENTER_ROOM_SUCCESS'
export const ENTER_ROOM_FAIL = 'ENTER_ROOM_FAIL'